=== Pierre-rigodiat/RDA/mgiml/mgiml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- GENERIC ELEMENTS -->
	<xs:complexType name="unit">
		<xs:sequence>
			<xs:element name="value" type="xs:double" />
			<xs:element name="unit" type="xs:string" />
			<xs:element name="error" type="error" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="error">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="amount|percentage" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- LEVEL 0 (root node) -->
	<xs:element name="experiment">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="datas" type="datas" />
				<xs:element name="materials" type="materials" />
				<xs:element name="preparation" type="preparation" />
				<xs:element name="temperature" type="unit" />
                <xs:element name="pressure" type="unit" />
                <xs:element name="duration" type="unit" />
				<xs:element name="properties" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- LEVEL 1 -->
	<xs:complexType name="datas">
		<xs:sequence>
			<xs:element name="id" type="xs:integer" />
			<xs:element name="type" type="xs:string" />
			<xs:element name="comment" type="xs:string" />
			<xs:element name="measuredParameters" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="materials">
		<xs:sequence>
			<xs:element name="constituents" type="constituents" />
			<xs:element name="diffusingSpecie" type="diffusingSpecie" />
			<xs:element name="phases" type="phases" />
			<xs:element name="bulkComposition" type="bulkComposition" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="preparation">
		<xs:sequence>
			<xs:element name="container" type="xs:string" />
			<xs:element name="samplePreparationMethod" type="xs:string" />
			<xs:element name="samplePreparationSteps" type="samplePreparationSteps" />
		</xs:sequence>
	</xs:complexType>

	<!-- LEVEL 2 (materials) -->
	<xs:complexType name="constituents">
		<xs:sequence>
			<xs:element name="constituent" type="xs:string" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="diffusingSpecie">
		<xs:sequence>
			<xs:element name="diffusingSpecie" type="xs:string" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="phases">
		<xs:sequence>
			<xs:element name="phase" type="phase" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bulkComposition">
		<xs:sequence>
			<xs:element name="constituent" type="xs:string" />
			<xs:element name="bulkFraction" type="xs:integer" />
			<xs:element name="materialPurity" type="xs:double" minOccurs="0" />
			<xs:element name="materialForm" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<!-- LEVEL 2 (preparation) -->
	<xs:complexType name="samplePreparationSteps">
		<xs:sequence>
			<xs:element name="samplePreparationStep" type="samplePreparationStep"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- LEVEL 3 (materials/phases) -->
	<xs:complexType name="phase">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="bulkFraction" type="xs:positiveInteger" />
			<xs:element name="crystalStructure" type="crystalStructure" />
		</xs:sequence>
	</xs:complexType>

	<!-- LEVEL 3 (preparation/samplePreparationSteps) -->
	<xs:complexType name="samplePreparationStep">
		<xs:sequence>
			<xs:element name="comment" type="xs:string" />
			<xs:element name="surround" type="bulkComposition" /><!-- Already 
				define up ahead -->
			<xs:element name="temperature" type="unit" minOccurs="0" /><!-- Already define 
				up ahead -->
			<xs:element name="pressure" type="unit" minOccurs="0" /><!-- Already define 
				up ahead -->
			<xs:element name="duration" type="unit" minOccurs="0" /><!-- Already define 
				up ahead -->
			<xs:element name="method" type="xs:string" />
			<xs:element name="container" type="xs:string" minOccurs="0" />
			<xs:element name="sampleGeometry" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- LEVEL 4 (materials/phases/phase/crystalStructure) -->
	<xs:complexType name="crystalStructure">
		<xs:sequence>
			<xs:element name="spaceGroup" type="xs:string" />
			<xs:element name="wyckoffSequence" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Pierre-rigodiat/RDA/mgiml/mgiml.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="draft.css"?>

<experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mgiml.xsd">
	<datas>
		<id>1</id>
		<type>self-diffusion</type>
		<comment>Radioactive tracer experiment</comment>
		<measuredParameters>self-diffusion of Ni in Ni; D* Ni</measuredParameters>
	</datas>
	<materials>
		<constituents>
			<constituent>Ni</constituent>
		</constituents>
		<phases>
			<phase>
				<name>FCC</name>
				<bulkFraction>1</bulkFraction>
				<crystalStructure>FCC</crystalStructure>
			</phase>
		</phases>
		<bulkComposition>
			<constituent>Ni</constituent>
			<bulkFraction>1</bulkFraction>
			<materialPurity>0.99997</materialPurity>
			<materialForm>single crystal</materialForm>
		</bulkComposition>
	</materials>
	<preparation>
		<container>Horizontal furnace with an at;osphere of pure Ar with 2% H2</container>
		<samplePreparationMethod>Radioactive tracer experiment with Ni63</samplePreparationMethod>
		<samplePreparationSteps>
			<samplePreparationStep>
				<comment>Producing single crystals</comment>
				<surround>
					<constituent>Ni</constituent>
					<bulkFraction>1</bulkFraction>
					<materialPurity>0.99997</materialPurity>
					<materialForm>single crystal</materialForm>
				</surround>
				<method>Bridgman</method>
				<container>5mm diameter cylinders</container>
			</samplePreparationStep>
			<samplePreparationStep>
				<comment>Anneal single crystal</comment>
				<surround>
					<constituent>Ni</constituent>
					<bulkFraction>1</bulkFraction>
					<materialPurity>0.99997</materialPurity>
					<materialForm>single crystal</materialForm>
				</surround>
				<temperature>
					<unit>K</unit>
					<value>1623</value>
				</temperature>
				<pressure>
					<unit>atm</unit>
					<value>1</value>
				</pressure>
				<method>annealing</method>
				<container>3mm thick disks</container>
			</samplePreparationStep>
			<samplePreparationStep>
				<comment>Apply thin layer of radioactive tracer</comment>
				<surround>
					<constituent>Ni63</constituent>
					<bulkFraction>1</bulkFraction>
					<materialForm>sputter deposited</materialForm>
				</surround>
				<method>iom-beam sputtering</method>
			</samplePreparationStep>
		</samplePreparationSteps>
	</preparation>
	<temperature>
		<unit>K</unit>
		<value>815.15</value>
		<error type="amount">0.2</error>
	</temperature>
	<pressure>
		<unit>atm</unit>
		<value>1</value>
	</pressure>
	<duration>
		<unit>s</unit>
		<value>945000</value>
		<error type="percentage">10</error>
	</duration>
	<properties>{Direct, serial sectioning, penetration profiles;2.5704E-22,m2/s,5%}</properties>
</experiment>
